/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dadDiary.ui;

import com.dadDiary.logics.BagTableLogic;
import com.dadDiary.logics.PurseTableLogic;
import com.dadDiary.logics.TotalBalanceLogic;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HP
 */
public class NewDiaryUI extends javax.swing.JFrame {

    /**
     * Creates new form NewDiaryUI
     */
    public NewDiaryUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        avlAccBalTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cnt2000NewBag = new javax.swing.JTextField();
        cnt500NewBag = new javax.swing.JTextField();
        cnt200NewBag = new javax.swing.JTextField();
        cnt100NewBag = new javax.swing.JTextField();
        cnt50NewBag = new javax.swing.JTextField();
        cnt20NewBag = new javax.swing.JTextField();
        cnt10NewBag = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        NewBagTotalTxt = new javax.swing.JTextField();
        NewBagTotalBtn = new javax.swing.JButton();
        Amnt2000NewBagTxt = new javax.swing.JTextField();
        Amnt500NewBagTxt = new javax.swing.JTextField();
        Amnt200NewBagTxt = new javax.swing.JTextField();
        Amnt100NewBagTxt = new javax.swing.JTextField();
        Amnt50NewBagTxt = new javax.swing.JTextField();
        Amnt20NewBagTxt = new javax.swing.JTextField();
        Amnt10NewBagTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cnt2000NewPurse = new javax.swing.JTextField();
        cnt500NewPurse = new javax.swing.JTextField();
        cnt200NewPurse = new javax.swing.JTextField();
        cnt100NewPurse = new javax.swing.JTextField();
        cnt50NewPurse = new javax.swing.JTextField();
        cnt20NewPurse = new javax.swing.JTextField();
        cnt10NewPurse = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        cnt5NewPurse = new javax.swing.JTextField();
        cnt2NewPurse = new javax.swing.JTextField();
        cnt1NewPurse = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        NewPurseTotalBtn = new javax.swing.JButton();
        NewPurseTotalTxt = new javax.swing.JTextField();
        Amnt2000NewPurseTxt = new javax.swing.JTextField();
        Amnt500NewPurseTxt = new javax.swing.JTextField();
        Amnt200NewPurseTxt = new javax.swing.JTextField();
        Amnt100NewPurseTxt = new javax.swing.JTextField();
        Amnt50NewPurseTxt = new javax.swing.JTextField();
        Amnt20NewPurseTxt = new javax.swing.JTextField();
        Amnt10NewPurseTxt = new javax.swing.JTextField();
        Amnt2NewPurseTxt = new javax.swing.JTextField();
        Amnt5NewPurseTxt = new javax.swing.JTextField();
        Amnt1NewPurseTxt = new javax.swing.JTextField();
        CreateNewDiaryButton = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Available Account Balance  :");

        avlAccBalTxt.setText("0000.00");
        avlAccBalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avlAccBalTxtActionPerformed(evt);
            }
        });

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Cash Details On Bag");

        jLabel3.setText("2000   x");

        jLabel4.setText("500     x");

        jLabel5.setText("200     x");

        jLabel6.setText("100     x");

        jLabel7.setText("50       x");

        jLabel8.setText("20       x");

        jLabel9.setText("10       x");

        cnt2000NewBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnt2000NewBagActionPerformed(evt);
            }
        });

        cnt500NewBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnt500NewBagActionPerformed(evt);
            }
        });

        cnt200NewBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnt200NewBagActionPerformed(evt);
            }
        });

        cnt100NewBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnt100NewBagActionPerformed(evt);
            }
        });

        cnt50NewBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnt50NewBagActionPerformed(evt);
            }
        });

        cnt20NewBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnt20NewBagActionPerformed(evt);
            }
        });

        cnt10NewBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnt10NewBagActionPerformed(evt);
            }
        });

        jLabel25.setText("=");

        jLabel26.setText("=");

        jLabel27.setText("=");

        jLabel28.setText("=");

        jLabel29.setText("=");

        jLabel30.setText("=");

        jLabel31.setText("=");

        NewBagTotalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBagTotalTxtActionPerformed(evt);
            }
        });

        NewBagTotalBtn.setText("Total");
        NewBagTotalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBagTotalBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NewBagTotalBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(NewBagTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnt500NewBag))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnt2000NewBag, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnt200NewBag))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnt100NewBag))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnt50NewBag))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnt20NewBag))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnt10NewBag)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Amnt2000NewBagTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Amnt500NewBagTxt))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Amnt200NewBagTxt))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Amnt100NewBagTxt))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Amnt50NewBagTxt))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Amnt10NewBagTxt))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Amnt20NewBagTxt)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cnt2000NewBag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(Amnt2000NewBagTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cnt500NewBag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Amnt500NewBagTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cnt200NewBag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(Amnt200NewBagTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cnt100NewBag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(Amnt100NewBagTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cnt50NewBag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(Amnt50NewBagTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cnt20NewBag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(Amnt20NewBagTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnt10NewBag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Amnt10NewBagTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewBagTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewBagTotalBtn))
                .addContainerGap())
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Cash Details On Purse");

        jLabel11.setText("2000   x");

        jLabel12.setText("500     x");

        jLabel13.setText("200     x");

        jLabel14.setText("100     x");

        jLabel15.setText("50       x");

        jLabel16.setText("20       x");

        jLabel17.setText("10       x");

        cnt2000NewPurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnt2000NewPurseActionPerformed(evt);
            }
        });

        cnt500NewPurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnt500NewPurseActionPerformed(evt);
            }
        });

        cnt200NewPurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnt200NewPurseActionPerformed(evt);
            }
        });

        cnt100NewPurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnt100NewPurseActionPerformed(evt);
            }
        });

        cnt50NewPurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnt50NewPurseActionPerformed(evt);
            }
        });

        cnt20NewPurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnt20NewPurseActionPerformed(evt);
            }
        });

        cnt10NewPurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnt10NewPurseActionPerformed(evt);
            }
        });

        jLabel18.setText("=");

        jLabel19.setText("=");

        jLabel20.setText("=");

        jLabel21.setText("=");

        jLabel22.setText("=");

        jLabel23.setText("=");

        jLabel24.setText("=");

        jLabel32.setText("5         x");

        jLabel33.setText("2         x");

        jLabel34.setText("1         x");

        cnt5NewPurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnt5NewPurseActionPerformed(evt);
            }
        });

        cnt2NewPurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnt2NewPurseActionPerformed(evt);
            }
        });

        cnt1NewPurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnt1NewPurseActionPerformed(evt);
            }
        });

        jLabel35.setText("=");

        jLabel36.setText("=");

        jLabel37.setText("=");

        NewPurseTotalBtn.setText("Total");
        NewPurseTotalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPurseTotalBtnActionPerformed(evt);
            }
        });

        Amnt2000NewPurseTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Amnt2000NewPurseTxtActionPerformed(evt);
            }
        });

        Amnt500NewPurseTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Amnt500NewPurseTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnt1NewPurse))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnt2NewPurse))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnt5NewPurse))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnt500NewPurse))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnt2000NewPurse, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnt200NewPurse))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnt100NewPurse))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnt50NewPurse))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnt20NewPurse))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnt10NewPurse)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Amnt2000NewPurseTxt))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Amnt500NewPurseTxt))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Amnt200NewPurseTxt))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Amnt100NewPurseTxt))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Amnt50NewPurseTxt))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Amnt20NewPurseTxt))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Amnt10NewPurseTxt))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel35)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Amnt5NewPurseTxt))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel37)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Amnt1NewPurseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel36)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Amnt2NewPurseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(NewPurseTotalBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(NewPurseTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cnt2000NewPurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(Amnt2000NewPurseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cnt500NewPurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(Amnt500NewPurseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cnt200NewPurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(Amnt200NewPurseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cnt100NewPurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(Amnt100NewPurseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cnt50NewPurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(Amnt50NewPurseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cnt20NewPurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(Amnt20NewPurseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cnt10NewPurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(Amnt10NewPurseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(cnt5NewPurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(Amnt5NewPurseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(cnt2NewPurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(Amnt2NewPurseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(cnt1NewPurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(Amnt1NewPurseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewPurseTotalBtn)
                    .addComponent(NewPurseTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        CreateNewDiaryButton.setText("Create");
        CreateNewDiaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewDiaryButtonActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText("New Diary");

        homeBtn.setText("HOME");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(CreateNewDiaryButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(avlAccBalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeBtn)
                        .addGap(42, 42, 42))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(homeBtn)
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(avlAccBalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(CreateNewDiaryButton)
                        .addGap(197, 197, 197))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avlAccBalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avlAccBalTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avlAccBalTxtActionPerformed

    private void cnt500NewBagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnt500NewBagActionPerformed
        Amnt500NewBagTxt.setText(String.valueOf(500*(Integer.parseInt(cnt500NewBag.getText()))));
    }//GEN-LAST:event_cnt500NewBagActionPerformed

    private void cnt200NewBagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnt200NewBagActionPerformed
        Amnt200NewBagTxt.setText(String.valueOf(200*(Integer.parseInt(cnt200NewBag.getText()))));
    }//GEN-LAST:event_cnt200NewBagActionPerformed

    private void cnt500NewPurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnt500NewPurseActionPerformed
        Amnt500NewPurseTxt.setText(String.valueOf(500*(Integer.parseInt(cnt500NewPurse.getText()))));
    }//GEN-LAST:event_cnt500NewPurseActionPerformed

    private void cnt200NewPurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnt200NewPurseActionPerformed
        Amnt200NewPurseTxt.setText(String.valueOf(200*(Integer.parseInt(cnt200NewPurse.getText()))));
    }//GEN-LAST:event_cnt200NewPurseActionPerformed

    private void Amnt500NewPurseTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Amnt500NewPurseTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Amnt500NewPurseTxtActionPerformed

    private void cnt20NewBagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnt20NewBagActionPerformed
        Amnt20NewBagTxt.setText(String.valueOf(20*(Integer.parseInt(cnt20NewBag.getText()))));
    }//GEN-LAST:event_cnt20NewBagActionPerformed

    private void NewBagTotalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBagTotalTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewBagTotalTxtActionPerformed

    private void Amnt2000NewPurseTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Amnt2000NewPurseTxtActionPerformed
       
    }//GEN-LAST:event_Amnt2000NewPurseTxtActionPerformed

    private void cnt2000NewPurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnt2000NewPurseActionPerformed
        Amnt2000NewPurseTxt.setText(String.valueOf(2000*(Integer.parseInt(cnt2000NewPurse.getText()))));
    }//GEN-LAST:event_cnt2000NewPurseActionPerformed

    private void cnt100NewPurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnt100NewPurseActionPerformed
        Amnt100NewPurseTxt.setText(String.valueOf(100*(Integer.parseInt(cnt100NewPurse.getText()))));
    }//GEN-LAST:event_cnt100NewPurseActionPerformed

    private void cnt50NewPurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnt50NewPurseActionPerformed
        Amnt50NewPurseTxt.setText(String.valueOf(50*(Integer.parseInt(cnt50NewPurse.getText()))));
    }//GEN-LAST:event_cnt50NewPurseActionPerformed

    private void cnt20NewPurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnt20NewPurseActionPerformed
        Amnt20NewPurseTxt.setText(String.valueOf(20*(Integer.parseInt(cnt20NewPurse.getText()))));
    }//GEN-LAST:event_cnt20NewPurseActionPerformed

    private void cnt10NewPurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnt10NewPurseActionPerformed
        Amnt10NewPurseTxt.setText(String.valueOf(10*(Integer.parseInt(cnt10NewPurse.getText()))));
    }//GEN-LAST:event_cnt10NewPurseActionPerformed

    private void cnt5NewPurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnt5NewPurseActionPerformed
        Amnt5NewPurseTxt.setText(String.valueOf(5*(Integer.parseInt(cnt5NewPurse.getText()))));
    }//GEN-LAST:event_cnt5NewPurseActionPerformed

    private void cnt2NewPurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnt2NewPurseActionPerformed
        Amnt2NewPurseTxt.setText(String.valueOf(2*(Integer.parseInt(cnt2NewPurse.getText()))));
    }//GEN-LAST:event_cnt2NewPurseActionPerformed

    private void cnt1NewPurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnt1NewPurseActionPerformed
        Amnt1NewPurseTxt.setText(String.valueOf(1*(Integer.parseInt(cnt1NewPurse.getText()))));
    }//GEN-LAST:event_cnt1NewPurseActionPerformed

    private void NewPurseTotalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPurseTotalBtnActionPerformed
        NewPurseTotalTxt.setText(String.valueOf(Integer.parseInt(Amnt2000NewPurseTxt.getText())+Integer.parseInt(Amnt500NewPurseTxt.getText())+Integer.parseInt(Amnt200NewPurseTxt.getText())+Integer.parseInt(Amnt100NewPurseTxt.getText())+Integer.parseInt(Amnt50NewPurseTxt.getText())+Integer.parseInt(Amnt20NewPurseTxt.getText())+Integer.parseInt(Amnt10NewPurseTxt.getText())+Integer.parseInt(Amnt5NewPurseTxt.getText())+Integer.parseInt(Amnt2NewPurseTxt.getText())+Integer.parseInt(Amnt1NewPurseTxt.getText())));
    }//GEN-LAST:event_NewPurseTotalBtnActionPerformed

    private void cnt2000NewBagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnt2000NewBagActionPerformed
        Amnt2000NewBagTxt.setText(String.valueOf(2000*(Integer.parseInt(cnt2000NewBag.getText()))));
    }//GEN-LAST:event_cnt2000NewBagActionPerformed

    private void cnt100NewBagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnt100NewBagActionPerformed
        Amnt100NewBagTxt.setText(String.valueOf(100*(Integer.parseInt(cnt100NewBag.getText()))));
    }//GEN-LAST:event_cnt100NewBagActionPerformed

    private void cnt50NewBagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnt50NewBagActionPerformed
        Amnt50NewBagTxt.setText(String.valueOf(50*(Integer.parseInt(cnt50NewBag.getText()))));
    }//GEN-LAST:event_cnt50NewBagActionPerformed

    private void cnt10NewBagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnt10NewBagActionPerformed
        Amnt10NewBagTxt.setText(String.valueOf(10*(Integer.parseInt(cnt10NewBag.getText()))));
    }//GEN-LAST:event_cnt10NewBagActionPerformed

    private void NewBagTotalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBagTotalBtnActionPerformed
        NewBagTotalTxt.setText(String.valueOf(Integer.parseInt(Amnt2000NewBagTxt.getText())+Integer.parseInt(Amnt500NewBagTxt.getText())+Integer.parseInt(Amnt200NewBagTxt.getText())+Integer.parseInt(Amnt100NewBagTxt.getText())+Integer.parseInt(Amnt50NewBagTxt.getText())+Integer.parseInt(Amnt20NewBagTxt.getText())+Integer.parseInt(Amnt10NewBagTxt.getText())));
    }//GEN-LAST:event_NewBagTotalBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomePageUI obj = new HomePageUI();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void CreateNewDiaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewDiaryButtonActionPerformed
        createNewBag();
        createNewPurse();
        createNewTotBalTable();
    }//GEN-LAST:event_CreateNewDiaryButtonActionPerformed
    
    public void createNewBag(){
        try {
            Date dt = new Date();
            SimpleDateFormat frmt = new SimpleDateFormat("dd/mm/yyyy");
            String dtStr = frmt.format(dt);
            Date date = frmt.parse(dtStr);
            int NewBag2000 = Integer.parseInt(cnt2000NewBag.getText());
            int NewBag500 = Integer.parseInt(cnt500NewBag.getText());
            int NewBag200 = Integer.parseInt(cnt200NewBag.getText());
            int NewBag100 = Integer.parseInt(cnt100NewBag.getText());
            int NewBag50 = Integer.parseInt(cnt50NewBag.getText());
            int NewBag20 = Integer.parseInt(cnt20NewBag.getText());
            int NewBag10 = Integer.parseInt(cnt10NewBag.getText());
            
            Boolean isSuccess = new BagTableLogic().createBag(date, NewBag2000, NewBag500, NewBag200, NewBag100, NewBag50, NewBag20, NewBag10);
            if(isSuccess){
                System.out.println("tabel Bag is created");
            }
            else{
                System.out.println("error bag creation");
            }
        } catch (ParseException ex) {
            Logger.getLogger(NewDiaryUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void createNewPurse(){
        try {
            Date dt = new Date();
            SimpleDateFormat frmt = new SimpleDateFormat("dd/mm/yyyy");
            String dtStr = frmt.format(dt);
            Date date = frmt.parse(dtStr);
            int NewPurse2000 = Integer.parseInt(cnt2000NewPurse.getText());
            int NewPurse500 = Integer.parseInt(cnt500NewPurse.getText());
            int NewPurse200 = Integer.parseInt(cnt200NewPurse.getText());
            int NewPurse100 = Integer.parseInt(cnt100NewPurse.getText());
            int NewPurse50 = Integer.parseInt(cnt50NewPurse.getText());
            int NewPurse20 = Integer.parseInt(cnt20NewPurse.getText());
            int NewPurse10 = Integer.parseInt(cnt10NewPurse.getText());
            int NewPurse5 = Integer.parseInt(cnt5NewPurse.getText());
            int NewPurse2 = Integer.parseInt(cnt2NewPurse.getText());
            int NewPurse1 = Integer.parseInt(cnt1NewPurse.getText());
            
            Boolean isSuccess = new PurseTableLogic().createPurse(date, NewPurse2000, NewPurse500, NewPurse200, NewPurse100, NewPurse50, NewPurse20, NewPurse10, NewPurse5, NewPurse2, NewPurse1);
            if(isSuccess){
                System.out.println("table Purse is created");
            }
            else{
                System.out.println("error purse creation");
            }} catch (ParseException ex) {
            Logger.getLogger(NewDiaryUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void createNewTotBalTable(){
        try {
            Date dt = new Date();
            SimpleDateFormat frmt = new SimpleDateFormat("dd/mm/yyyy");
            String dtStr = frmt.format(dt);
            Date date = frmt.parse(dtStr);
            long NewPurseTotal = Long.parseLong(NewPurseTotalTxt.getText());
            long NewBagTotal = Long.parseLong(NewBagTotalTxt.getText());
            long NewBankTotal = Long.parseLong(avlAccBalTxt.getText());
            
            Boolean isSuccess = new TotalBalanceLogic().createTotalBalTable(date, NewBagTotal, NewBankTotal, NewPurseTotal);
            if(isSuccess){
                System.out.println("table total balance is created");
            }
            else
            {
                System.out.println("error total bal table creation");
            }
        } catch (ParseException ex) {
            Logger.getLogger(NewDiaryUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewDiaryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewDiaryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewDiaryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewDiaryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewDiaryUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Amnt100NewBagTxt;
    private javax.swing.JTextField Amnt100NewPurseTxt;
    private javax.swing.JTextField Amnt10NewBagTxt;
    private javax.swing.JTextField Amnt10NewPurseTxt;
    private javax.swing.JTextField Amnt1NewPurseTxt;
    private javax.swing.JTextField Amnt2000NewBagTxt;
    private javax.swing.JTextField Amnt2000NewPurseTxt;
    private javax.swing.JTextField Amnt200NewBagTxt;
    private javax.swing.JTextField Amnt200NewPurseTxt;
    private javax.swing.JTextField Amnt20NewBagTxt;
    private javax.swing.JTextField Amnt20NewPurseTxt;
    private javax.swing.JTextField Amnt2NewPurseTxt;
    private javax.swing.JTextField Amnt500NewBagTxt;
    private javax.swing.JTextField Amnt500NewPurseTxt;
    private javax.swing.JTextField Amnt50NewBagTxt;
    private javax.swing.JTextField Amnt50NewPurseTxt;
    private javax.swing.JTextField Amnt5NewPurseTxt;
    private javax.swing.JButton CreateNewDiaryButton;
    private javax.swing.JButton NewBagTotalBtn;
    private javax.swing.JTextField NewBagTotalTxt;
    private javax.swing.JButton NewPurseTotalBtn;
    private javax.swing.JTextField NewPurseTotalTxt;
    private javax.swing.JTextField avlAccBalTxt;
    private javax.swing.JTextField cnt100NewBag;
    private javax.swing.JTextField cnt100NewPurse;
    private javax.swing.JTextField cnt10NewBag;
    private javax.swing.JTextField cnt10NewPurse;
    private javax.swing.JTextField cnt1NewPurse;
    private javax.swing.JTextField cnt2000NewBag;
    private javax.swing.JTextField cnt2000NewPurse;
    private javax.swing.JTextField cnt200NewBag;
    private javax.swing.JTextField cnt200NewPurse;
    private javax.swing.JTextField cnt20NewBag;
    private javax.swing.JTextField cnt20NewPurse;
    private javax.swing.JTextField cnt2NewPurse;
    private javax.swing.JTextField cnt500NewBag;
    private javax.swing.JTextField cnt500NewPurse;
    private javax.swing.JTextField cnt50NewBag;
    private javax.swing.JTextField cnt50NewPurse;
    private javax.swing.JTextField cnt5NewPurse;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
